name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          node-version: '17.2.x'
      - name: Build
        id: build
        run: |
          npm install
          npm run build --prod        
      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_BEACH_0F7B6F403 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "./F1-backoffice" # App source code path
          output_location: "angular.json#$.projects[*].architect.build.options.outputPath" # Built app content directory - optional
          app_build_command: 'ng build'
          ###### End of Repository/Build Configurations ######
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          # Action to perform
          action: "upload"
          # Directory location of the application source code
          app_location: "./F1-backoffice"
          # Required token
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_VICTORIOUS_BEACH_0F7B6F403 }}
          # Directory location of the Azure Functions source code
          app_artifact_location: .
          # Directory location of the compiled application code after building
          output_location: .
          # Custom command for Oryx to run when building application source code          
